[target.i686-unknown-linux-gnu]
linker = "i686-linux-gnu-gcc"
ar = "i686-linux-gnu-ar"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
ar = "aarch64-linux-gnu-ar"

[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"
ar = "arm-linux-gnueabihf-ar"

[target.x86_64-unknown-linux-musl]
linker = "rust-lld"

# MIPS big-endian Linux GNU
[target.mips-unknown-linux-gnu]
linker = "mips-linux-gnu-gcc"
ar = "mips-linux-gnu-ar"

[target.loongarch64-unknown-linux-gnu]
linker = "loongarch64-linux-gnu-gcc"
ar = "loongarch64-linux-gnu-ar"